<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    /**
     * Seed initial services data into database.
     */
    public function run(): void
    {
        $services = [
            // Trauma & Emergency
            [
                'title' => 'Trauma & Accident Care',
                'slug' => 'trauma-and-accident-care',
                'category' => 'trauma',
                'category_label' => 'Trauma & Emergency',
                'color' => 'rose',
                'badge' => '24/7 Emergency',
                'image' => 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80',
                'desc' => 'Round-the-clock emergency response for severe polytrauma, open fractures, and life-threatening musculoskeletal injuries with dedicated emergency OTs.',
                'features' => ['Level-1 Emergency Facility', '24/7 On-Call Trauma Surgeons', 'Instant ICU & Blood Bank Access'],
                'is_active' => true,
            ],
            [
                'title' => 'Pelvis & Acetabulum Fracture Management',
                'slug' => 'pelvic-and-acetabular-fracture-management',
                'category' => 'trauma',
                'category_label' => 'Trauma & Emergency',
                'color' => 'rose',
                'badge' => 'Complex Reconstruction',
                'image' => 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
                'desc' => 'High-precision surgical fixation and minimally invasive reconstruction for complex pelvic ring and acetabular socket fractures.',
                'features' => ['3D CT Pre-Surgical Mapping', 'Minimally Invasive Fixation', 'Early Mobilization Protocols'],
                'is_active' => true,
            ],
            [
                'title' => 'Nerve, Artery & Tendon Injury Management',
                'slug' => 'nerve-artery-tendon-injury-management',
                'category' => 'trauma',
                'category_label' => 'Trauma & Emergency',
                'color' => 'rose',
                'badge' => 'Micro-Vascular Surgery',
                'image' => 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=800&q=80',
                'desc' => 'Micro-surgical repair and nerve grafting for traumatic severed tendons, peripheral nerve injuries, and acute vascular extremity trauma.',
                'features' => ['Operating Microscope Precision', 'Nerve Conduction Guidance', 'Specialized Hand & Micro-Surgeons'],
                'is_active' => true,
            ],

            // Spine & Back Care
            [
                'title' => 'Spine Injury Management',
                'slug' => 'spine-injury-management',
                'category' => 'spine',
                'category_label' => 'Spine & Back Care',
                'color' => 'sky',
                'badge' => 'Trauma & Stabilization',
                'image' => 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&w=800&q=80',
                'desc' => 'Comprehensive emergency and elective care for spinal cord trauma, vertebral fractures, and spinal instability to preserve neurological function.',
                'features' => ['Intraoperative Neuromonitoring', 'Percutaneous Spine Fixation', 'Spinal Cord Injury ICU'],
                'is_active' => true,
            ],
            [
                'title' => 'Cervical, Thoracic & Lumbar Spine Disorders',
                'slug' => 'cervical-thoracic-lumbar-spine-disorders',
                'category' => 'spine',
                'category_label' => 'Spine & Back Care',
                'color' => 'sky',
                'badge' => 'Comprehensive Spine',
                'image' => 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
                'desc' => 'Expert diagnosis and multi-disciplinary treatment for herniated discs, spinal stenosis, spondylolisthesis, and degenerative spine disease across all regions.',
                'features' => ['Cervical Disc Replacement', 'Lumbar Fusion (TLIF/PLIF)', 'Non-Surgical Pain Therapies'],
                'is_active' => true,
            ],

            [
                'title' => 'Back Pain Treatment',
                'slug' => 'back-pain-treatment',
                'category' => 'spine',
                'category_label' => 'Spine & Back Care',
                'color' => 'sky',
                'badge' => 'Non-Surgical & Intervention',
                'image' => 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80',
                'desc' => 'Targeted non-surgical therapies, epidural steroid injections, facet joint radiofrequency ablation, and specialized core spine rehab for chronic back pain.',
                'features' => ['Fluoroscopy-Guided Injections', 'Radiofrequency Ablation', 'Ergonomic & Spine Rehab'],
                'is_active' => true,
            ],
            [
                'title' => 'Spine Deformity Correction',
                'slug' => 'spine-deformity-correction',
                'category' => 'spine',
                'category_label' => 'Spine & Back Care',
                'color' => 'sky',
                'badge' => 'Scoliosis & Kyphosis',
                'image' => 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
                'desc' => 'Advanced corrective spinal surgery for adolescent & adult scoliosis, kyphosis, and post-traumatic spinal deformities using 3D navigation.',
                'features' => ['3D O-Arm Intraoperative CT', 'Neuromonitoring Safety', 'Cosmetic Alignment Focus'],
                'is_active' => true,
            ],

            // Joint Replacements
            [
                'title' => 'Knee Replacement Surgery',
                'slug' => 'knee-replacement-surgery',
                'category' => 'joints',
                'category_label' => 'Joint Replacements',
                'color' => 'blue',
                'badge' => 'Advanced & Conventional',
                'image' => 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
                'desc' => 'Precision-guided total and partial knee replacement ensuring sub-millimeter implant precision, natural knee feel, and rapid walking.',
                'features' => ['3D Pre-Op Planning', 'Muscle-Sparing Technique', 'Walk within 24 Hours'],
                'is_active' => true,
            ],
            [
                'title' => 'Hip Replacement Surgery',
                'slug' => 'hip-replacement-surgery',
                'category' => 'joints',
                'category_label' => 'Joint Replacements',
                'color' => 'blue',
                'badge' => 'Direct Anterior Option',
                'image' => 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80',
                'desc' => 'Total hip replacement using ceramic-on-ceramic long-life implants and muscle-preserving direct anterior approach for accelerated rehabilitation.',
                'features' => ['Direct Anterior Approach', 'Ceramic Ultra-Durable Bearings', 'Minimal Post-Op Restrictions'],
                'is_active' => true,
            ],
            [
                'title' => 'Shoulder Replacement Surgery',
                'slug' => 'shoulder-replacement-surgery',
                'category' => 'joints',
                'category_label' => 'Joint Replacements',
                'color' => 'blue',
                'badge' => 'Anatomic & Reverse',
                'image' => 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=800&q=80',
                'desc' => 'Anatomic and reverse total shoulder arthroplasty for severe glenohumeral arthritis, cuff tear arthropathy, and complex proximal humerus fractures.',
                'features' => ['Reverse Shoulder Expertise', 'Patient-Specific Implants', 'Restores Overhead Reach'],
                'is_active' => true,
            ],
            [
                'title' => 'Elbow Replacement Surgery',
                'slug' => 'elbow-replacement-surgery',
                'category' => 'joints',
                'category_label' => 'Joint Replacements',
                'color' => 'blue',
                'badge' => 'Sub-Specialized',
                'image' => 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
                'desc' => 'Total elbow arthroplasty for debilitating rheumatoid arthritis, severe post-traumatic joint destruction, and un-united distal humerus fractures.',
                'features' => ['Linked & Unlinked Options', 'Restores Functional Range', 'Dedicated Upper Limb Unit'],
                'is_active' => true,
            ],

            // Sports Medicine & Arthroscopy
            [
                'title' => 'Sports Injury Treatment',
                'slug' => 'sports-injury-treatment',
                'category' => 'sports',
                'category_label' => 'Sports Medicine',
                'color' => 'indigo',
                'badge' => 'Athlete Protocol',
                'image' => 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
                'desc' => 'Advanced medical and physical care tailored for professional and recreational athletes, covering acute sprains, muscle tears, and over-use syndromes.',
                'features' => ['Biomechanical Gait Analysis', 'Biological PRP Therapy', 'Return-to-Sport Assessment'],
                'is_active' => true,
            ],
            [
                'title' => 'Ligament & Meniscus Tear Treatment',
                'slug' => 'ligament-and-meniscus-tear-treatment',
                'category' => 'sports',
                'category_label' => 'Sports Medicine',
                'color' => 'indigo',
                'badge' => 'ACL / PCL / Meniscus',
                'image' => 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
                'desc' => 'Keyhole reconstructive procedures for ACL, PCL, MCL, LCL tears and meniscus repair or preservation using autograft/allograft tissue.',
                'features' => ['Anatomic ACL Reconstruction', 'Meniscal Repair Preservation', 'Accelerated Rehab Track'],
                'is_active' => true,
            ],
            [
                'title' => 'Arthroscopic Surgery',
                'slug' => 'arthroscopic-surgery',
                'category' => 'sports',
                'category_label' => 'Sports Medicine',
                'color' => 'indigo',
                'badge' => 'Keyhole Joint Care',
                'image' => 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
                'desc' => 'Diagnostic and therapeutic keyhole surgery for knee, shoulder, hip, ankle, and wrist joints through HD cameras and micro-instruments.',
                'features' => ['HD 4K Visualization', 'Minimal Post-Op Pain', 'Day-Care Surgery Option'],
                'is_active' => true,
            ],

            // Specialized Care & Rehab
            [
                'title' => 'Foot & Ankle Surgery',
                'slug' => 'foot-and-ankle-surgery',
                'category' => 'specialized',
                'category_label' => 'Specialized & Rehab',
                'color' => 'emerald',
                'badge' => 'Reconstructive Foot',
                'image' => 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80',
                'desc' => 'Comprehensive treatment for ankle arthritis, Achilles tendon ruptures, bunions (hallux valgus), flatfoot deformities, and diabetic foot conditions.',
                'features' => ['Ankle Arthroscopy & Fusion', 'Bunion Correction Surgery', 'Diabetic Foot Care Unit'],
                'is_active' => true,
            ],
            [
                'title' => 'Congenital Foot Deformity Correction',
                'slug' => 'congenital-foot-deformity-correction',
                'category' => 'specialized',
                'category_label' => 'Specialized & Rehab',
                'color' => 'emerald',
                'badge' => 'Pediatric & Deformity',
                'image' => 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80',
                'desc' => 'Non-surgical Ponseti casting and surgical correction for congenital clubfoot (CTEV), vertical talus, and pediatric gait abnormalities.',
                'features' => ['Ponseti Method Experts', 'Tendon Transfer Surgery', 'Child-Centric Rehab Suite'],
                'is_active' => true,
            ],
            [
                'title' => 'Rheumatology Services',
                'slug' => 'rheumatology-services',
                'category' => 'specialized',
                'category_label' => 'Specialized & Rehab',
                'color' => 'emerald',
                'badge' => 'Autoimmune & Joints',
                'image' => 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=800&q=80',
                'desc' => 'Specialized medical diagnosis and biologic targeted therapy for Rheumatoid Arthritis, Ankylosing Spondylitis, Gout, Lupus, and Osteoporosis.',
                'features' => ['Biologic Targeted Infusions', 'Bone Densitometry (DEXA)', 'Joint Preservation Focus'],
                'is_active' => true,
            ],
            [
                'title' => 'Joint Pain & Swelling Treatment',
                'slug' => 'joint-pain-and-swelling-treatment',
                'category' => 'specialized',
                'category_label' => 'Specialized & Rehab',
                'color' => 'emerald',
                'badge' => 'Early Arthritis & PRP',
                'image' => 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
                'desc' => 'Comprehensive evaluation of unexplained joint effusion, cartilage wear, and early osteoarthritis utilizing Platelet-Rich Plasma (PRP) and hyaluronic injections.',
                'features' => ['Ultrasound-Guided Injections', 'Platelet-Rich Plasma (PRP)', 'Viscosupplementation'],
                'is_active' => true,
            ],
            [
                'title' => 'Physiotherapy & Rehabilitation',
                'slug' => 'physiotherapy-and-rehabilitation',
                'category' => 'specialized',
                'category_label' => 'Specialized & Rehab',
                'color' => 'emerald',
                'badge' => 'Advanced Hydro & Physio',
                'image' => 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80',
                'desc' => 'State-of-the-art physical rehab facility equipped with hydrotherapy pools, advanced gait trainers, laser therapy, and customized post-op recovery plans.',
                'features' => ['Advanced Gait Training', 'Hydrotherapy Rehabilitation', '1-on-1 Dedicated Physio'],
                'is_active' => true,
            ],
        ];

        foreach ($services as $data) {
            Service::updateOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
